import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { Brain, Sparkles, RotateCcw, Check, X, Loader2, LogIn, LogOut, History, Users, KeyRound } from "lucide-react";
import { generateQuiz, type QuizQuestion } from "@/lib/quiz.functions";
import { saveQuizResult } from "@/lib/quiz-results.functions";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/use-auth";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Progress } from "@/components/ui/progress";
import { toast } from "sonner";
import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";


export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "QuizForge — AI-powered MCQ exams on any topic" },
      { name: "description", content: "Enter any topic and instantly take a multiple-choice exam generated by AI." },
      { property: "og:title", content: "QuizForge — AI MCQ exams" },
      { property: "og:description", content: "Enter any topic and instantly take a multiple-choice exam generated by AI." },
    ],
  }),
  component: Home,
});

type Stage = "setup" | "exam" | "results";

function Home() {
  const [stage, setStage] = useState<Stage>("setup");
  const [topic, setTopic] = useState("");
  const [count, setCount] = useState(5);
  const [difficulty, setDifficulty] = useState<"easy" | "medium" | "hard">("medium");
  const [questions, setQuestions] = useState<QuizQuestion[]>([]);
  const [current, setCurrent] = useState(0);
  const [answers, setAnswers] = useState<number[]>([]);
  const [saved, setSaved] = useState(false);
  const { user } = useAuth();
  const navigate = useNavigate();

  const mutation = useMutation({
    mutationFn: (vars: { topic: string; count: number; difficulty: "easy" | "medium" | "hard" }) =>
      generateQuiz({ data: vars }),
    onSuccess: (res) => {
      setQuestions(res.questions);
      setAnswers(new Array(res.questions.length).fill(-1));
      setCurrent(0);
      setSaved(false);
      setStage("exam");
    },
    onError: (err: Error) => toast.error(err.message || "Failed to generate quiz"),
  });

  const saveMutation = useMutation({
    mutationFn: (payload: {
      topic: string;
      difficulty: "easy" | "medium" | "hard";
      score: number;
      totalQuestions: number;
      questions: QuizQuestion[];
      answers: number[];
    }) => saveQuizResult({ data: payload }),
    onSuccess: () => {
      setSaved(true);
      toast.success("Result saved to your history.");
    },
    onError: (e: Error) => toast.error(e.message || "Failed to save result"),
  });


  const start = (e: React.FormEvent) => {
    e.preventDefault();
    if (topic.trim().length < 2) {
      toast.error("Enter a topic (at least 2 characters).");
      return;
    }
    mutation.mutate({ topic: topic.trim(), count, difficulty });
  };

  const reset = () => {
    setStage("setup");
    setQuestions([]);
    setAnswers([]);
    setCurrent(0);
    setSaved(false);
  };

  const score = answers.reduce(
    (s, a, i) => (a === questions[i]?.correctIndex ? s + 1 : s),
    0,
  );

  const submitExam = () => {
    setStage("results");
    if (user && !saved) {
      saveMutation.mutate({
        topic: topic.trim(),
        difficulty,
        score: answers.reduce((s, a, i) => (a === questions[i]?.correctIndex ? s + 1 : s), 0),
        totalQuestions: questions.length,
        questions,
        answers,
      });
    }
  };

  const signOut = async () => {
    await supabase.auth.signOut();
    toast.success("Signed out.");
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-background via-background to-accent/30">
      <Toaster richColors position="top-center" />
      <header className="border-b border-border/60 backdrop-blur-sm">
        <div className="mx-auto flex max-w-5xl items-center justify-between px-6 py-4">
          <div className="flex items-center gap-2">
            <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary text-primary-foreground">
              <Brain className="h-5 w-5" />
            </div>
            <span className="text-lg font-semibold tracking-tight">QuizForge</span>
          </div>
          <nav className="flex items-center gap-1 sm:gap-2">
            <Button asChild variant="ghost" size="sm">
              <Link to="/join"><KeyRound className="mr-2 h-4 w-4" /> Join Exam</Link>
            </Button>
            {user ? (
              <>
                <Button asChild variant="ghost" size="sm">
                  <Link to="/exams"><Users className="mr-2 h-4 w-4" /> Host</Link>
                </Button>
                <Button asChild variant="ghost" size="sm">
                  <Link to="/history"><History className="mr-2 h-4 w-4" /> History</Link>
                </Button>
                <Button variant="ghost" size="sm" onClick={signOut}>
                  <LogOut className="mr-2 h-4 w-4" /> Sign out
                </Button>
              </>
            ) : (
              <Button variant="outline" size="sm" onClick={() => navigate({ to: "/auth" })}>
                <LogIn className="mr-2 h-4 w-4" /> Sign in
              </Button>
            )}
          </nav>
        </div>
      </header>


      <main className="mx-auto max-w-3xl px-6 py-10">
        {stage === "setup" && (
          <div>
            <div className="mb-8 text-center">
              <h1 className="text-4xl font-bold tracking-tight sm:text-5xl">
                Turn any topic into an <span className="text-primary">MCQ exam</span>
              </h1>
              <p className="mt-3 text-muted-foreground">
                Type a subject, pick difficulty, and get a fresh multiple-choice quiz in seconds.
              </p>
            </div>

            <Card className="shadow-lg">
              <CardHeader>
                <CardTitle>Create your exam</CardTitle>
                <CardDescription>Anything from &quot;World War II&quot; to &quot;React hooks&quot;.</CardDescription>
              </CardHeader>
              <CardContent>
                <form onSubmit={start} className="space-y-5">
                  <div className="space-y-2">
                    <Label htmlFor="topic">Topic</Label>
                    <Input
                      id="topic"
                      placeholder="e.g. Photosynthesis, Ancient Rome, JavaScript closures…"
                      value={topic}
                      onChange={(e) => setTopic(e.target.value)}
                      maxLength={120}
                      autoFocus
                    />
                  </div>

                  <div className="grid gap-4 sm:grid-cols-2">
                    <div className="space-y-2">
                      <Label htmlFor="count">Questions</Label>
                      <Input
                        id="count"
                        type="number"
                        min={1}
                        max={50}
                        value={count}
                        onChange={(e) => {
                          const n = Number(e.target.value);
                          setCount(Number.isFinite(n) ? Math.max(1, Math.min(50, Math.floor(n))) : 1);
                        }}
                      />
                    </div>

                    <div className="space-y-2">
                      <Label>Difficulty</Label>
                      <Select value={difficulty} onValueChange={(v) => setDifficulty(v as "easy" | "medium" | "hard")}>
                        <SelectTrigger><SelectValue /></SelectTrigger>
                        <SelectContent>
                          <SelectItem value="easy">Easy</SelectItem>
                          <SelectItem value="medium">Medium</SelectItem>
                          <SelectItem value="hard">Hard</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                  </div>

                  <Button type="submit" size="lg" className="w-full" disabled={mutation.isPending}>
                    {mutation.isPending ? (
                      <><Loader2 className="mr-2 h-4 w-4 animate-spin" /> Generating your quiz…</>
                    ) : (
                      <><Sparkles className="mr-2 h-4 w-4" /> Generate Quiz</>
                    )}
                  </Button>
                </form>
              </CardContent>
            </Card>
          </div>
        )}

        {stage === "exam" && questions.length > 0 && (
          <ExamView
            questions={questions}
            current={current}
            answers={answers}
            topic={topic}
            onSelect={(i) => {
              const next = [...answers];
              next[current] = i;
              setAnswers(next);
            }}
            onPrev={() => setCurrent((c) => Math.max(0, c - 1))}
            onNext={() => setCurrent((c) => Math.min(questions.length - 1, c + 1))}
            onSubmit={submitExam}
          />
        )}

        {stage === "results" && (
          <ResultsView
            questions={questions}
            answers={answers}
            score={score}
            topic={topic}
            onRestart={reset}
            saveStatus={
              !user
                ? "signed-out"
                : saveMutation.isPending
                  ? "saving"
                  : saved
                    ? "saved"
                    : saveMutation.isError
                      ? "error"
                      : "idle"
            }
          />
        )}

      </main>
    </div>
  );
}

function ExamView({
  questions, current, answers, topic, onSelect, onPrev, onNext, onSubmit,
}: {
  questions: QuizQuestion[];
  current: number;
  answers: number[];
  topic: string;
  onSelect: (i: number) => void;
  onPrev: () => void;
  onNext: () => void;
  onSubmit: () => void;
}) {
  const q = questions[current];
  const progress = ((current + 1) / questions.length) * 100;
  const isLast = current === questions.length - 1;
  const answered = answers[current] !== -1;
  const allAnswered = answers.every((a) => a !== -1);

  return (
    <Card className="shadow-lg">
      <CardHeader>
        <div className="flex items-center justify-between text-sm text-muted-foreground">
          <span className="font-medium text-foreground">{topic}</span>
          <span>Question {current + 1} of {questions.length}</span>
        </div>
        <Progress value={progress} className="mt-2 h-2" />
      </CardHeader>
      <CardContent className="space-y-6">
        <h2 className="text-xl font-semibold leading-snug">{q.question}</h2>
        <RadioGroup
          value={answers[current] === -1 ? "" : String(answers[current])}
          onValueChange={(v) => onSelect(Number(v))}
          className="space-y-2"
        >
          {q.options.map((opt, i) => (
            <label
              key={i}
              className={cn(
                "flex cursor-pointer items-center gap-3 rounded-lg border p-4 transition-colors hover:bg-accent",
                answers[current] === i && "border-primary bg-accent",
              )}
            >
              <RadioGroupItem value={String(i)} id={`opt-${i}`} />
              <span className="text-sm">{opt}</span>
            </label>
          ))}
        </RadioGroup>

        <div className="flex items-center justify-between pt-2">
          <Button variant="outline" onClick={onPrev} disabled={current === 0}>Previous</Button>
          {isLast ? (
            <Button onClick={onSubmit} disabled={!allAnswered}>Submit Exam</Button>
          ) : (
            <Button onClick={onNext} disabled={!answered}>Next</Button>
          )}
        </div>
      </CardContent>
    </Card>
  );
}

function ResultsView({
  questions, answers, score, topic, onRestart, saveStatus,
}: {
  questions: QuizQuestion[];
  answers: number[];
  score: number;
  topic: string;
  onRestart: () => void;
  saveStatus: "idle" | "saving" | "saved" | "error" | "signed-out";
}) {
  const pct = Math.round((score / questions.length) * 100);
  const verdict = pct >= 80 ? "Excellent!" : pct >= 60 ? "Nice work." : pct >= 40 ? "Keep practicing." : "Let's try again.";

  return (
    <div className="space-y-6">
      <Card className="shadow-lg">
        <CardHeader className="text-center">
          <CardDescription>{topic}</CardDescription>
          <CardTitle className="text-3xl">{verdict}</CardTitle>
        </CardHeader>
        <CardContent className="text-center">
          <div className="text-6xl font-bold text-primary">{score}<span className="text-2xl text-muted-foreground">/{questions.length}</span></div>
          <p className="mt-2 text-muted-foreground">{pct}% correct</p>
          <div className="mt-4 text-xs text-muted-foreground">
            {saveStatus === "saving" && <span className="inline-flex items-center"><Loader2 className="mr-1 h-3 w-3 animate-spin" /> Saving to history…</span>}
            {saveStatus === "saved" && <span className="text-green-600">✓ Saved to your history</span>}
            {saveStatus === "error" && <span className="text-destructive">Couldn&apos;t save to history</span>}
            {saveStatus === "signed-out" && (
              <span>
                <Link to="/auth" className="text-primary underline">Sign in</Link> to save your results.
              </span>
            )}
          </div>
          <Button onClick={onRestart} className="mt-6" size="lg">
            <RotateCcw className="mr-2 h-4 w-4" /> New Quiz
          </Button>
        </CardContent>
      </Card>


      <div className="space-y-3">
        <h3 className="text-lg font-semibold">Review</h3>
        {questions.map((q, i) => {
          const chosen = answers[i];
          const correct = chosen === q.correctIndex;
          return (
            <Card key={i}>
              <CardContent className="space-y-3 py-5">
                <div className="flex items-start gap-3">
                  <div className={cn(
                    "mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full",
                    correct ? "bg-green-500/15 text-green-600" : "bg-destructive/15 text-destructive",
                  )}>
                    {correct ? <Check className="h-4 w-4" /> : <X className="h-4 w-4" />}
                  </div>
                  <p className="font-medium">{i + 1}. {q.question}</p>
                </div>
                <div className="ml-9 space-y-1 text-sm">
                  {q.options.map((opt, j) => (
                    <div key={j} className={cn(
                      "rounded-md px-3 py-1.5",
                      j === q.correctIndex && "bg-green-500/10 text-green-700 dark:text-green-400",
                      j === chosen && j !== q.correctIndex && "bg-destructive/10 text-destructive",
                    )}>
                      {opt}
                      {j === q.correctIndex && <span className="ml-2 text-xs">(correct)</span>}
                      {j === chosen && j !== q.correctIndex && <span className="ml-2 text-xs">(your answer)</span>}
                    </div>
                  ))}
                  {q.explanation && (
                    <p className="pt-2 text-muted-foreground">{q.explanation}</p>
                  )}
                </div>
              </CardContent>
            </Card>
          );
        })}
      </div>
    </div>
  );
}
