/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JoinRouteImport } from './routes/join'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamCodeRouteImport } from './routes/exam.$code'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedExamsIndexRouteImport } from './routes/_authenticated/exams/index'
import { Route as AuthenticatedExamsExamIdRouteRouteImport } from './routes/_authenticated/exams/$examId.route'
import { Route as AuthenticatedExamsExamIdIndexRouteImport } from './routes/_authenticated/exams/$examId.index'
import { Route as AuthenticatedExamsExamIdResultsRouteImport } from './routes/_authenticated/exams/$examId.results'

const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamCodeRoute = ExamCodeRouteImport.update({
  id: '/exam/$code',
  path: '/exam/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamsIndexRoute = AuthenticatedExamsIndexRouteImport.update({
  id: '/exams/',
  path: '/exams/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamsExamIdRouteRoute =
  AuthenticatedExamsExamIdRouteRouteImport.update({
    id: '/exams/$examId',
    path: '/exams/$examId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExamsExamIdIndexRoute =
  AuthenticatedExamsExamIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedExamsExamIdRouteRoute,
  } as any)
const AuthenticatedExamsExamIdResultsRoute =
  AuthenticatedExamsExamIdResultsRouteImport.update({
    id: '/results',
    path: '/results',
    getParentRoute: () => AuthenticatedExamsExamIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/exam/$code': typeof ExamCodeRoute
  '/exams/$examId': typeof AuthenticatedExamsExamIdRouteRouteWithChildren
  '/exams/': typeof AuthenticatedExamsIndexRoute
  '/exams/$examId/results': typeof AuthenticatedExamsExamIdResultsRoute
  '/exams/$examId/': typeof AuthenticatedExamsExamIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/exam/$code': typeof ExamCodeRoute
  '/exams': typeof AuthenticatedExamsIndexRoute
  '/exams/$examId/results': typeof AuthenticatedExamsExamIdResultsRoute
  '/exams/$examId': typeof AuthenticatedExamsExamIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/exam/$code': typeof ExamCodeRoute
  '/_authenticated/exams/$examId': typeof AuthenticatedExamsExamIdRouteRouteWithChildren
  '/_authenticated/exams/': typeof AuthenticatedExamsIndexRoute
  '/_authenticated/exams/$examId/results': typeof AuthenticatedExamsExamIdResultsRoute
  '/_authenticated/exams/$examId/': typeof AuthenticatedExamsExamIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/join'
    | '/history'
    | '/exam/$code'
    | '/exams/$examId'
    | '/exams/'
    | '/exams/$examId/results'
    | '/exams/$examId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/join'
    | '/history'
    | '/exam/$code'
    | '/exams'
    | '/exams/$examId/results'
    | '/exams/$examId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/join'
    | '/_authenticated/history'
    | '/exam/$code'
    | '/_authenticated/exams/$examId'
    | '/_authenticated/exams/'
    | '/_authenticated/exams/$examId/results'
    | '/_authenticated/exams/$examId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  JoinRoute: typeof JoinRoute
  ExamCodeRoute: typeof ExamCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$code': {
      id: '/exam/$code'
      path: '/exam/$code'
      fullPath: '/exam/$code'
      preLoaderRoute: typeof ExamCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/': {
      id: '/_authenticated/exams/'
      path: '/exams'
      fullPath: '/exams/'
      preLoaderRoute: typeof AuthenticatedExamsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/$examId': {
      id: '/_authenticated/exams/$examId'
      path: '/exams/$examId'
      fullPath: '/exams/$examId'
      preLoaderRoute: typeof AuthenticatedExamsExamIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/$examId/': {
      id: '/_authenticated/exams/$examId/'
      path: '/'
      fullPath: '/exams/$examId/'
      preLoaderRoute: typeof AuthenticatedExamsExamIdIndexRouteImport
      parentRoute: typeof AuthenticatedExamsExamIdRouteRoute
    }
    '/_authenticated/exams/$examId/results': {
      id: '/_authenticated/exams/$examId/results'
      path: '/results'
      fullPath: '/exams/$examId/results'
      preLoaderRoute: typeof AuthenticatedExamsExamIdResultsRouteImport
      parentRoute: typeof AuthenticatedExamsExamIdRouteRoute
    }
  }
}

interface AuthenticatedExamsExamIdRouteRouteChildren {
  AuthenticatedExamsExamIdResultsRoute: typeof AuthenticatedExamsExamIdResultsRoute
  AuthenticatedExamsExamIdIndexRoute: typeof AuthenticatedExamsExamIdIndexRoute
}

const AuthenticatedExamsExamIdRouteRouteChildren: AuthenticatedExamsExamIdRouteRouteChildren =
  {
    AuthenticatedExamsExamIdResultsRoute: AuthenticatedExamsExamIdResultsRoute,
    AuthenticatedExamsExamIdIndexRoute: AuthenticatedExamsExamIdIndexRoute,
  }

const AuthenticatedExamsExamIdRouteRouteWithChildren =
  AuthenticatedExamsExamIdRouteRoute._addFileChildren(
    AuthenticatedExamsExamIdRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedExamsExamIdRouteRoute: typeof AuthenticatedExamsExamIdRouteRouteWithChildren
  AuthenticatedExamsIndexRoute: typeof AuthenticatedExamsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedExamsExamIdRouteRoute:
    AuthenticatedExamsExamIdRouteRouteWithChildren,
  AuthenticatedExamsIndexRoute: AuthenticatedExamsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  JoinRoute: JoinRoute,
  ExamCodeRoute: ExamCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
